spring.application.name=marketplace-service
server.port=8097

spring.datasource.url=jdbc:postgresql://localhost:5432/alphintra_auth
spring.datasource.username=myapp
spring.datasource.password=alphintra123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY:}
