-- Create databases
CREATE DATABASE alphintra_auth;
CREATE DATABASE alphintra_wallet;
CREATE DATABASE alphintra_trading;
CREATE DATABASE alphintra_ticketing;

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE alphintra_auth TO myapp;
GRANT ALL PRIVILEGES ON DATABASE alphintra_wallet TO myapp;
GRANT ALL PRIVILEGES ON DATABASE alphintra_trading TO myapp;
GRANT ALL PRIVILEGES ON DATABASE alphintra_ticketing TO myapp;

-- Connect to each database and grant schema privileges
\c alphintra_auth;
GRANT ALL ON SCHEMA public TO myapp;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO myapp;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO myapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO myapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO myapp;

\c alphintra_wallet;
GRANT ALL ON SCHEMA public TO myapp;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO myapp;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO myapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO myapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO myapp;

\c alphintra_trading;
GRANT ALL ON SCHEMA public TO myapp;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO myapp;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO myapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO myapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO myapp;

\c alphintra_ticketing;
GRANT ALL ON SCHEMA public TO myapp;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO myapp;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO myapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO myapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO myapp;
